### ISSUE TITLE
extract of rootfs and user1 file

### ISSUE THREAD

**Issue by sylvain121** [c3c/miracast#2]
I,
Thank for your repo, it help me to understand functionement of amlogic system.
I have a mirascreen dongle with amlogic 8252.
After getting firmware I, have extract user1 and rootfs file, but i don't know how to access files inside.

Do you have some's details about that ?
Tanks

**Comment by c3c** [comment]
How did you extract the firmware? 
Generally, using e.g. firmware-mod-kit you can extract firmware, then the rootfs directory should contain the Linux filesystem that you're used to.

**Comment by sylvain121** [comment]
I download fireware from this link : cdn.iezvu.com/upgrade/am8252_nand_mirascreen/am8252_nand_mirascreen-16397000.gz
I use actions-firmware-extract from your repo to extract rootfs and user1.
But I am not able to mount in a loop device that 2 files with ext4 or 2.
File command was unable to determine fs type.

I will try to use firmware-mod-kit to extract firmware.
Thank's :)
